2021-06-12 23:21:55,238 [main.py         | 48] INFO: Start to run instance_1
2021-06-12 23:21:55,238 [simulate_api.py | 60] INFO: Start time of the simulator: 2021-06-12 00:00:00, time interval:  600.00
2021-06-12 23:21:55,250 [input_utils.py  | 48] INFO: Get 154 factories
2021-06-12 23:21:56,848 [input_utils.py  | 52] INFO: Get 23562 routes
2021-06-12 23:21:56,875 [input_utils.py  | 57] INFO: Get 5 vehicles
2021-06-12 23:21:56,885 [input_utils.py  | 61] INFO: Get 50 orders
2021-06-12 23:21:56,886 [simulate_api.py | 87] INFO: Initial position of V_1 is e2d5093fbe36431f8986ddb0e1c586be
2021-06-12 23:21:56,888 [simulate_api.py | 87] INFO: Initial position of V_2 is 7fe14b93f0f04ee7a994ef5b2c1fdb72
2021-06-12 23:21:56,888 [simulate_api.py | 87] INFO: Initial position of V_3 is fa366fc87a124d32926daa5bb093129f
2021-06-12 23:21:56,888 [simulate_api.py | 87] INFO: Initial position of V_4 is e47399648fa842b2b8f80094343d8091
2021-06-12 23:21:56,888 [simulate_api.py | 87] INFO: Initial position of V_5 is becb4f85393540b287e7329758b8d832
2021-06-12 23:21:56,889 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:21:56,889 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 00:10:00, pre time: 2021-06-12 00:00:00
2021-06-12 23:21:56,889 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 00:10:00
2021-06-12 23:21:56,889 [simulate_environment.py | 163] INFO: Get 1 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-12 23:21:57,920 [simulate_environment.py | 247] INFO: 2021-06-12 00:10:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-12 23:21:57,920 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:21:57,920 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 00:20:00, pre time: 2021-06-12 00:10:00
2021-06-12 23:21:57,920 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 00:20:00
2021-06-12 23:21:57,928 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-12 23:21:59,277 [simulate_environment.py | 247] INFO: 2021-06-12 00:20:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-12 23:21:59,277 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:21:59,277 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 00:30:00, pre time: 2021-06-12 00:20:00
2021-06-12 23:21:59,277 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 00:30:00
2021-06-12 23:21:59,286 [simulate_environment.py | 163] INFO: Get 3 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-12 23:22:00,614 [simulate_environment.py | 247] INFO: 2021-06-12 00:30:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-12 23:22:00,615 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:22:00,615 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 00:40:00, pre time: 2021-06-12 00:30:00
2021-06-12 23:22:00,615 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 00:40:00
2021-06-12 23:22:00,631 [simulate_environment.py | 163] INFO: Get 9 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-12 23:22:02,328 [simulate_environment.py | 247] INFO: 2021-06-12 00:40:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-12 23:22:02,328 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:22:02,328 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 00:50:00, pre time: 2021-06-12 00:40:00
2021-06-12 23:22:02,329 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 00:50:00
2021-06-12 23:22:02,334 [simulate_environment.py | 163] INFO: Get 9 unallocated order items, 0 ongoing order items, 0 completed order items
2021-06-12 23:22:03,998 [simulate_environment.py | 247] INFO: 2021-06-12 00:50:00, Item 0003480001-1: state = 1 < 2, we can not finish the simulation
2021-06-12 23:22:03,998 [simulate_environment.py | 96] INFO: **************************************************
2021-06-12 23:22:03,998 [simulate_environment.py | 100] INFO: cur time: 2021-06-12 01:00:00, pre time: 2021-06-12 00:50:00
2021-06-12 23:22:03,998 [simulate_environment.py | 136] INFO: Start to update the input of 2021-06-12 01:00:00
2021-06-12 23:22:04,005 [simulate_environment.py | 163] INFO: Get 4 unallocated order items, 5 ongoing order items, 0 completed order items
2021-06-12 23:22:05,180 [simulate_environment.py | 240] ERROR: 2021-06-12 23:22:05,117 [main_algorithm.py | 32] ERROR: Failed to run algorithm
2021-06-12 23:22:05,118 [main_algorithm.py | 33] ERROR: Error: '2445d4bd004c457d95957d6ecf77f759', Traceback (most recent call last):
  File "main_algorithm.py", line 29, in <module>
    scheduling()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\vrppd\main_algorithm.py", line 162, in scheduling
    data_transfomer.__solution_algo_2_sim(vehicle_route,
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\data_transfomer\data_transfomer.py", line 194, in __solution_algo_2_sim
    __reset_destination(vehicles_info_map, vehicleID, customers, destination, route[0], update_time)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\algorithm\data_transfomer\data_transfomer.py", line 170, in __reset_destination
    lng, lat = customers[factory_id].getPosition[0], customers[factory_id].getPosition[1]
KeyError: '2445d4bd004c457d95957d6ecf77f759'

FAIL

2021-06-12 23:22:05,180 [main.py         | 55] ERROR: Failed to run simulator
2021-06-12 23:22:05,180 [main.py         | 56] ERROR: Error: 未寻获算法输出成功标识SUCCESS, Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/dpdp/simulator/dpdp_competition/main.py", line 51, in <module>
    score = simulate(Configs.factory_info_file, Configs.route_info_file, instance)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_api.py", line 94, in simulate
    simulate_env.run()
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 107, in run
    used_seconds, dispatch_result = self.dispatch(updated_input_info)
  File "C:\Users\Administrator\Desktop\dpdp\simulator\dpdp_competition\src\simulator\simulate_environment.py", line 241, in dispatch
    raise ValueError('未寻获算法输出成功标识SUCCESS')
ValueError: 未寻获算法输出成功标识SUCCESS

